#!/bin/sh

SIZE=$(stat -c %s "$2")

cat <<EOF >"$1"
load mmc 0:1 \$kernel_addr_r \$kernel_file
load mmc 0:1 \${fdt_addr_r} \${soc}-colibri-\${fdt_board}.dtb
load mmc 0:1 \$ramdisk_addr_r imagefile.cpio.gz
setenv bootargs rdinit=/sbin/init root=/dev/ram initrd=\$ramdisk_addr_r,$SIZE
bootz \${kernel_addr_r} - \${fdt_addr_r}
EOF
