#!/bin/bash

set -e

cd "$(dirname "$0")"/..

BUILD_TOP=$(pwd)/build

trap 'make BUILD_TOP=$BUILD_TOP clean-all' EXIT

make BUILD_TOP=$BUILD_TOP default docs  &&
make BUILD_TOP=$BUILD_TOP upgrade  &&
mv build/boot .
