#!/bin/sh

# Simple network startup using configuration in /etc/network/interface.

. /etc/init.d/functions

do_start()
{
    ifup lo
    [ -e /etc/hostname ] && hostname $(cat /etc/hostname)
    ifup eth0
}

do_stop()
{
    ifdown eth0
}

do_start_stop "$@" networking
