#!/bin/sh

# Script to trigger upgrade of root file system.  This configures the u-boot
# environment to load and execute the upgrade-script.

Error() { echo >&2 "$@"; exit 1; }

# Retrieve named file from TFTP server
tftp_get()
{
    echo "Reading $1 from $TFTP_SERVER ($serverip)"
    tftp -g -l $TEMPFILE -r "$TFTP_PREFIX"$1 $serverip  ||
        Error "Unable to read $TFTP_PREFIX$1"
}


TFTP_PREFIX=/
TFTP_SERVER=none

# Pick up defaults
[ -e /etc/upgrade.config ]  &&
source /etc/upgrade.config

UPGRADE_STATE=0
TEST_FILES=true
CONFIRM=false
REBOOT_NOW=false

# Process options
while getopts 'P:S:prfCh' option; do
    case "$option" in
        P)  TFTP_PREFIX="$OPTARG" ;;
        S)  TFTP_SERVER="$OPTARG" ;;
        p)  UPGRADE_STATE=1 ;;
        f)  TEST_FILES=false ;;
        r)  REBOOT_NOW=true ;;
        C)  CONFIRM=true ;;
        h)  cat <<EOF
Usage: upgrade-rootfs [options]

Configures upgrade of root file system from tftp server.
    -P: Specify TFTP prefix (default is $TFTP_PREFIX)
    -S: Specify TFTP server (default is $TFTP_SERVER)
    -p  If this flag is set then the persistent state will be replaced.
    -f  This flag can be set to bypass validation of the upgrade files on the
        tftp server.
    -r  If set then reboot will be triggered immediately.
    -C  This flag must be set to confirm the upgrade, otherwise the upgrade will
        be tested but not actually applied.
EOF
            exit 0 ;;
        *)  Error 'Invalid option: try -h for help' ;;
    esac
done


# Normalise the server name and check it is responding
set -o pipefail
serverip="$(getent hosts "$TFTP_SERVER" | sed 's/ .*//')"  ||
    Error Unable to look up TFTP server "$TFTP_SERVER"


# Check that we can read all the requested files
if $TEST_FILES; then
    TEMPFILE=$(mktemp)
    trap 'rm -f $TEMPFILE' EXIT

    echo Validating upgrade files on TFTP server
    tftp_get zImage
    tftp_get device-tree.dtb
    tftp_get rootfs.img
    if [ $UPGRADE_STATE = 1 ]; then
        tftp_get state.img
    fi
fi


# We need to hand control over to u-boot to do the rootfs upgrade.
if $CONFIRM; then
    # Pick up our ethernet configuration
    ipaddr=$(ifconfig eth0 | sed -n '/.* addr:/{s///; s/ .*//; p;q}')
    netmask=$(ifconfig eth0 | sed -n '/.* Mask:/{s///; s/ .*//; p;q}')
    gatewayip=$(ip route | sed -n '/default via /{s///; s/ .*//; p;q}')

    # Update the u-boot environment
    cat <<EOF |
ipaddr $ipaddr
netmask $netmask
gatewayip $gatewayip
serverip $serverip
server_prefix $TFTP_PREFIX
write_state $UPGRADE_STATE
bootcmd tftpboot \$scriptaddr \${server_prefix}upgrade-script.image  &&  \
source \$scriptaddr
EOF
    fw_setenv -s /dev/stdin  &&
    # Go!
    $REBOOT_NOW  &&  reboot
fi
